routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/employee', 'employeeController@testFunc');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('holidays', 'Holiday\HolidayRequestController');
Route::post('holidays/{id}/approve', 'Holiday\HolidayRequestController@approve')->name('approve');
Route::post('holidays/{id}/cancell', 'Holiday\HolidayRequestController@cancell')->name('cancell');
Auth::routes();

Route::get('holidays/mailable/preview', function () {
  return new App\Mail\HolidayRequestNotification();
});

Route::get('holidays/index', 'Holiday\HolidayRequestController@index');
Route::get('holidays/mailable/send', 'Holiday\HolidayRequestController@sendRequestMail');

app/Models/HolidayType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class HolidayType extends Model
{
    protected $guarded = ['id'];
}

app/Http/Controllers/Holiday/HolidayRequestController.php
<?php

namespace App\Http\Controllers\Holiday;

use Illuminate\Http\Request;
use App\Models\Employee;
use App\Models\HolidayType;
use App\Models\HolidayRequest;
use Illuminate\Support\Facades\Mail;
use App\Mail\HolidayRequestNotification;
use App\Http\Requests\HolidayRequestRequest;
use App\Http\Controllers\Controller;

class HolidayRequestController extends Controller
{

    protected $holidayRequest;

    /**
     * コンストラクタインジェクション
     * @param repository $employees
     * @return void
     */
    public function __construct(HolidayRequest $holidayRequest)
    {
        $this->holidayRequest = $holidayRequest;
    }

    /**
     * 休暇申請の初期処理
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // 管理者の場合は全ての休暇申請レコードを取得する
        if(\Auth::user()->role_id != 3)
        {
            $holidays = HolidayRequest::orderBy('created_at', 'desc')
                ->simplePaginate(10);
        } 
        else
        {
        // ユーザーの場合は従業員コードに紐づくレコードのみ取得する
            $holidays = HolidayRequest::where('employee_id', \Auth::user()
                ->employee->id)->orderBy('created_at', 'desc')->simplePaginate(10);
        }

        return view('holidays.index', ['holidays' => $holidays]);
    }

    /**
     * 休暇申請の表示処理
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // プルダウンリストを変数に格納する
        $options = HolidayType::all();
        return view('holidays.create',['options' => $options]);
    }

    /**
     * 休暇申請の新規作成処理
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(HolidayRequestRequest $request)
    {
        $holiday = new HolidayRequest;
        $holiday->fill($request->all());

        // 現在ログイン中のユーザーに紐付く従業員IDを取得する
        $holiday->employee_id = \Auth::user()->employee->id;
        $holiday->save();

        // 申請報告メールを管理者に送信する
        $this->sendRequestMail($holiday);

        // リダイレクト処理
        return redirect('holidays')->with('success_message', '申請が完了しました');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 休暇申請の削除処理
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        HolidayRequest::find($id)->delete();
        return redirect('holidays')->with('success_message', '削除が完了しました');
    }

    /**
     * 休暇取得承認処理
     *
     * @param  int  $id
     * @return void
     */
    public function approve($id)
    {
        // 休暇申請済みフラグをtrueに切り替える
        HolidayRequest::find($id)->update(['is_approved' => true]);

        // リダイレクト処理
        return redirect('holidays')->with('success_message', '休暇の承認処理が行われました');

    }

    /**
     * 休暇取消申請処理
     *
     * @param  int  $id
     * @return void
     */
    public function cancell($id)
    {
        // 休暇取消申請済みフラグをtrueに切り替える
        HolidayRequest::find($id)->update(['is_cancelled' => true]);

        // リダイレクト処理を行う
        return redirect('holidays')->with('success_message', '休暇取得の取消申請処理が行われました');

    }

    /**
     * 休暇申請報告メールの送信
     *
     * @param  int  $id
     * @return void
     */
    public function sendRequestMail(object $data)
    {
        $request_employee = $data->employee->employee_name;
        $formated_date = date('Y年m月d日', strtotime($data->request_date));

        // メール本文を作成する
        $text  = "以下内容の休暇申請が送信されました。確認をお願い致します。\n\n";
        $text .= "申請者：" . $data->employee->employee_name . "\n";
        $text .= "申請日：" . $formated_date . "\n";
        $text .= "休暇種別：" . $data->holidayType->holiday_name . "\n\n";
        $text .= "よろしくお願い致します。";

        // 改行コードを変換する
        $text = nl2br($text);

        // 送信先の定義
        $to = 't.adachi.carecon@gmail.com'; // テスト用として自分のアドレスを使用

        // mailable を使ってメール送信を行う
        Mail::to($to)->send(new HolidayRequestNotification($request_employee, $text));
    } 
}

app/Http/Controllers/Holiday/HolidayRequestNotificationController.php
<?php

namespace App\Http\Controllers\Holiday;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;
use App\Mail\HolidayRequestNotification;

class HolidayRequestNotificationController extends Controller
{
    public function index()
    {
        $name = 'ララベル太郎';
        $text = 'これからもよろしくお願いいたします。';
        $to = 'taigabox@gmail.com';
        Mail::to($to)->send(new HolidayRequestNotification($name, $text));
    }
}

resources/views/holidays/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">新規作成</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{-- 申請フォームここから --}}

                    <form method="POST" action="{{ route('holidays.store') }}">
                        @csrf

                        {{-- 休暇取得日ここから --}}

                        <div class="form-group row">
                            <label for="request_date" class="col-md-4 col-form-label text-md-right">取得日</label>

                            <div class="col-md-6">
                                <input id="request_date" type="date" class="form-control @error('request_date') is-invalid @enderror" name="request_date" value="{{ old('request_date') }}" required autocomplete="" autofocus>

                                @error('request_date')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        {{-- 休暇取得日ここまで --}}

                        {{-- 休暇種別ここから --}}

                        <div class="form-group row">
                            <label for="holiday_type_id" class="col-md-4 col-form-label text-md-right">種別</label>

                            <div class="col-md-6">
                                <select id="holiday_type_id" class="form-control @error('holiday_type_id') is-invalid @enderror" name="holiday_type_id" value="{{ old('holiday_type_id') }}" required autocomplete="holiday_type_id">

                                @foreach($options as $option)
                                <option value="{{ $option->id }}">{{ $option->holiday_name }}</option>
                                @endforeach

                                </select>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        {{-- 休暇種別ここまで --}}

                        {{-- 申請ボタンここから --}}
                        
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    申請する
                                </button>
                            </div>
                        </div>

                        {{-- 申請ボタンここまで --}}

                    </form>

                    {{-- 申請フォームここまで --}}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/holidays/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">休暇申請</div>

                {{-- ユーザーのみ休暇申請ボタンを表示ここから --}}
                <div class="card-body">
                    @if(\Auth::user()->role_id == 3)
                    <a href="{{ route('holidays.create') }}"><button type="button" class="btn btn-primary" >休暇を申請する</button></a>
                    @endif
                </div>
                {{-- ユーザーのみ休暇申請ボタンを表示ここまで --}}

                <div class="card-body">
                    @include('holidays.show')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/holidays/show.blade.php
<table class="table">
    <thead>
        <tr>
            <th>取得日</th>
            @unless(\Auth::user()->role_id == 3)
            <th>取得者</th>
            @endunless
            <th>休暇種別</th>
            <th>ステータス</th>
            <th>申請日時</th>
            @unless(\Auth::user()->role_id == 3)
            <th></th>
            <th></th>
            @endunless
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach($holidays as $holiday)
        <tr>
            <td>{{ $holiday->request_date }}</td>
            @unless(\Auth::user()->role_id == 3)
            <td>{{ $holiday->employee->employee_name }}</td>
            @endunless
            <td>{{ $holiday->holidayType->holiday_name }}</td>
            <td>{{ $holiday->is_approved ? ($holiday->is_cancelled ? "取消申請中" : "承認済み") : "申請中" }}</td>
            <td>{{ $holiday->created_at }}</td>

            {{-- 管理者権限ユーザーのみ表示ここから --}}

            @unless(\Auth::user()->role_id == 3)

                {{-- 承認ボタン制御ここから --}}

                    {{-- 承認済みならばボタンは非活性とする --}}
                    @if($holiday->is_approved)
                    <td>
                        <button type="button" class="btn btn-primary" data-holiday="{{ $holiday->id }}" data-toggle="modal" data-target="#myModal" disabled>承認済み</button>
                    </td>

                    {{-- 未承認ならばボタンは活性とする --}}
                    @else
                    <td>
                        <form style="display:inline" method="post" action="holidays/{{ $holiday->id }}/approve">
                            @csrf
                            <input type="hidden" id="holiday-id" name="id" value="{{ $holiday->id }}">
                            <button type="submit" class="btn btn-primary">承認する</button>
                        </form>
                    </td>

                    @endif

                {{-- 取消確定ボタン制御ここまで --}}

                    {{-- 取消申請済ならば取消確認ボタンを表示する --}}

                    @if($holiday->is_cancelled)
                    <td>
                        <button type="button" class="btn btn-danger" data-holiday="{{ $holiday->id }}" data-toggle="modal" data-target="#deleteModal">取消確定</button>
                    </td>


                    {{-- 取消未申請ならば取消確認ボタンは表示しない --}}
                    @else
                    @endif

                {{-- 取消確定ボタン制御ここから --}}



                {{-- 承認ボタン制御ここまで --}}


            {{-- 管理者権限ユーザーのみ表示ここまで --}}

            {{-- ユーザー権限ユーザーのみ表示ここから --}}

            @else
                {{-- 削除ボタン制御ここから --}}

                    {{-- すでに承認済みの場合は削除ボタンは表示しない --}}
                    @if($holiday->is_approved)
                    {{-- 未承認の場合は削除ボタンを表示する --}}
                    @else
                        <td>
                            <button type="button" class="btn btn-danger" data-holiday="{{ $holiday->id }}" data-toggle="modal" data-target="#deleteModal">削除</button>
                        </td>
                    @endif
                {{-- 削除ボタン制御ここまで --}}


                {{-- 申請取消ボタン制御ここから --}}
                    {{-- すでに承認済みの場合は申請取消ボタンを表示する --}}
                    @if($holiday->is_approved)

                        {{-- 取消申請が申請済みであればボタンを非活性化する --}}
                        @if($holiday->is_cancelled)
                        <td>
                        <button type="button" class="btn btn-danger" data-holiday="{{ $holiday->id }}" data-toggle="modal" data-target="#cancellModal" disabled>取消申請</button></td>
                        @else
                        {{-- 取消申請が未申請であればボタンを活性化する --}}
                        <td>
                        <button type="button" class="btn btn-danger" data-holiday="{{ $holiday->id }}" data-toggle="modal" data-target="#cancellModal">取消申請</button></td>
                        @endif
                    @else
                    @endif

                {{-- 申請取消ボタン制御ここまで --}}

            @endunless

            {{-- ユーザー権限ユーザーのみ表示ここから --}}
        </tr>
        @endforeach
    </tbody>
</table>
{{ $holidays->links() }}